### PR TITLE
add an openai compatible api

### LINKED ISSUE #62: Feature request: clean the code and make a fastapi just like OpenAI's tts API
Hi, as the LLM got popular, we really want the text can have a voice,

EmotiVoice get the best quality and varianty on Chinese voice tts, there is no such a model can make this better.

As a result, it could be very fun and nice for your team to make it further, integrate it with LLMs. By just make this code more stable, ready for production, and make server as a TTS api just like OpenAI's.

### PR DESCRIPTION
**Pull request by lewangdev**

### CODE REVIEW

**Comment by syq163** [comment]
Great job! I'm excited to set up the environment, but I encountered an issue with Python 3.8. Could you please confirm if  PR is compatible with Python 3.8, as it's the recommended version to run with EmotiVoice?

**Comment by lewangdev** [comment]
OK，I will test it on Python 3.8.

**Comment by syq163** [comment]
> Hi, I configured my development environment using the Docker image `syq163/emoti-voice:latest`, which has Python version 3.10.12.
> 
> I used FastAPI to implement the openai compatible API for emoti-voice. And Python 3.10+ has the best and simplest syntax for type hints.
> 
> I will change to Python 3.8+ type hints to run with EmotiVoice.

Thank you for the information. Yeah, I agree 3.10+ might be better.

**Comment by lewangdev** [comment]
Great! 

it's amazing to see that you have already finished the changes so quickly. I'm sorry that I didn't have time today to modify and support Python 3.8.

log-config.yml is unnecessary and can be deleted. 

I agree that you keep 'frontend_cn.py' unchanged.

**Comment by syq163** [comment]
Thank you for confirming that. Could you please make the necessary updates as we discussed, so that I can easily merge the PR?

> Great!
> 
> it's amazing to see that you have already finished the changes so quickly. I'm sorry that I didn't have time today to modify and support Python 3.8.
> 
> log-config.yml is unnecessary and can be deleted.
> 
> I agree that you keep 'frontend_cn.py' unchanged.

**Comment by lewangdev** [comment]
Hi, the PR has been updated.

**Comment by syq163** [comment]
Thank you and all the best!

**Comment by newbei** [comment]
Can give a demo?

**Comment by qqedp045** [comment]
curl -X POST -H "Content-Type: application/json" -d '{"voice":"8051","input":"这里有一个改进的版本，使用了一个简单的轮询机制来等待文件生成。"}' http://192.168.21.133:8000/v1/audio/speech > o.mp3
@newbei 
    input: str
    voice: str = '8051'
    prompt: Optional[str] = ''
    language: Optional[str] = 'zh_us'
    model: Optional[str] = 'emoti-voice'
    response_format: Optional[str] = 'mp3'
    speed: Optional[float] = 1.0
    
还有其他参数，我最想知道的是prompt的用处。

**Comment by qqedp045** [comment]
def openai_audio(text: str, outPath: str):
    headers = {
        'Content-Type':'application/json'
    }
    url = "http://XXXXXXXX:8080/v1/audio/speech"
    query = {
                "model":"emoti-voice",
                "input":text,
                "voice":"984",
                "response_format":"mp3",
                "speed":1,
            }
    response = requests.post(url=url, data=json.dumps(query), headers=headers)
    # 保存文件
    f = open(outPath, "wb")
    f.write(response.content)
    f.close()

**Comment by xushilundao** [comment]
this is a test API cpde and it works,you can copy and paste it:
import requests
import json

def openai_audio(text: str, outPath: str):
    headers = {
        'Content-Type': 'application/json'
    }
    url = "http://localhost:8000/v1/audio/speech"
    query = {
        "model": "emoti-voice",
        "input": text,  # 使用传入的文本参数
        "voice": "984",
        "response_format": "mp3",
        "speed": 1,
    }
    response = requests.post(url=url, data=json.dumps(query), headers=headers)
    
    # 检查请求是否成功
    if response.status_code == 200:
        # 保存文件
        with open(outPath, "wb") as f:
            f.write(response.content)
        print(f"Audio saved to {outPath}")
    else:
        print(f"Failed to get audio. Status code: {response.status_code}")
        print(f"Response: {response.text}")

# 主程序调用部分
if __name__ == "__main__":
    text = "调试成功，调用TTS成功"
    output_path = "output.mp3"
    openai_audio(text, output_path)

**Comment by xushilundao** [comment]
> _ No description provided. _
I've already run this API code correctly ,but how can I integrate with this to the config file of  火火兔 ?
Cause there is NO key in the api file. How can I config the TTS section in docker-compose.yml?

image

**Pull request merged**
